### ISSUE TITLE
Fails to compile with Crystal 0.35.1

### ISSUE THREAD

**Issue by codehearts** [repomaa/ketchup#1]
I came across this project in the AUR while looking for a pomodoro timer and I'm super impressed with the thoroughness and architecture! Unfortunately, trying to install ketchup-git fails because it depends on crystal-git which is way newer than whatever version was out in 2016 and, weirdly, ketchup-bin also failed to install (but I didn't look into it)

I'll be putting up a PR for this in a minute or two, but I wanted to open an issue just for tracking and to see what the maintenance status of this project is

**Comment by repomaa** [comment]
Thanks for the kind words! To be honest I’ve totally forgotten about this Project. So that probably answers your question about the maintanence status. Would you be interested nicht taking over? :)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by repomaa** [comment]
Closing since it’s fixed by your PR.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by codehearts** [comment]
I'm not super familiar with Crystal, but I wouldn't mind taking over! I noticed the PKGBUILD needs libyaml as a dependency and I've been thinking of adding a status format arg (I'm currently using `sed` to format it nicely for polyvar), so it'd at least get some love in the near future

**Comment by repomaa** [comment]
Ok sweet! Plus, if this helps to grow the awesome crystal community, all the better! :) I'll transfer ownership to you. What's your AUR username?

**Comment by codehearts** [comment]
Haha, it's definitely an interesting language! I hadn't touched Ruby in years so it was fun getting back into it. My AUR username is `codehearts`
